import type { NextPage } from 'next'
import { useEffect, useState } from 'react'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import { get, add } from '../../src/hooks/useLocalStorage'

const key = 'page history'
const Main: NextPage = () => {
  const [, setHistories] = useState<string[]>([])
  useEffect(() => {
    const history = get(key)
    const newData = history instanceof Array ? history : [history]
    add(key, JSON.stringify([...newData, 'main']))
    setHistories(newData)
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Main
        </h1>
      </main>
    </div>
  )
}

export default Main
