import type { NextPage } from 'next'
import { useRouter } from 'next/router'
import { useEffect, useRef, useState } from 'react'
import jsQR from 'jsqr'
import Head from 'next/head'
import { useReadContext } from '../../src/components/ReadContext'
import styles from '../../styles/Home.module.css'

const Read: NextPage = () => {
  const router = useRouter()
  const { updateResult } = useReadContext()
  const videoRef =  useRef<HTMLVideoElement>(null)
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const [stream, setStream] = useState<MediaStream | null>(null)

  const onClick = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia(
        {
          audio: false,
          video: { facingMode: 'environment' }
        }
      )
      setStream(stream)
      const video = videoRef.current
      if (!video) return
      video.srcObject = stream
      video.onloadedmetadata = () => {
        video.play()
        checkQr()
      }
    } catch (e) {
      console.log('=== ERROR', e)
    }
  }
  const checkQr = () => {
    const canvas = canvasRef.current
    const video = videoRef.current
    if (!canvas || !video) return
    const ctx = canvas.getContext('2d')
    ctx?.drawImage(video, 0, 0, canvas.width, canvas.height)
    const imageData = ctx?.getImageData(0, 0, canvas.width, canvas.height)
    if (!imageData) return
    const code = jsQR(imageData.data, canvas.width, canvas.height)

    if (code) {
      updateResult(code?.data ?? '')
      router.push('/result')
    } else {
      setTimeout( () => {
        checkQr()
      }, 1000)
    }
  }
  useEffect(() => {
    return () => {
      stream?.getVideoTracks().forEach(t => t.stop())
    }
  }, [stream])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          QR
        </h1>
        <button onClick={() => onClick()}>カメラを起動</button>
        <video className={styles.video}  ref={videoRef}></video>
        <canvas className={styles.canvas} ref={canvasRef} />
      </main>
    </div>
  )
}

export default Read
