import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Top ver.14
        </h1>
        <div className={styles.linkWrap}>
          <Link href='/main'>Mainへ</Link>
          <Link href='/sub'>Subへ</Link>
        </div>
      </main>
    </div>
  )
}

export default Home
