import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const current = new Date().toString()
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Top 2021/12/14
        </h1>
        <div>{current}</div>
        <div className={styles.linkWrap}>
          <Link href='/read'>画像読み取りへ</Link>
        </div>
      </main>
    </div>
  )
}

export default Home
