import type { NextPage } from 'next'
import { useRouter } from 'next/router'
import { useState } from 'react'
import Head from 'next/head'
import { useReadContext } from '../../../src/components/ReadContext'
import styles from '../../../styles/Home.module.css'
import { Html5Qrcode } from 'html5-qrcode'

const HtmlQr: NextPage = () => {
  const router = useRouter()
  const { updateResult } = useReadContext()
  const [error, setError] = useState('')
  const onClick = async () => {
    try {
      const devices = await Html5Qrcode.getCameras()
      if (!devices || devices.length < 1) {
        return
      }
      const cameraId = devices[0].id
      const html5QrCode = new Html5Qrcode('reader')
      html5QrCode.start(
        cameraId,
        {
          fps: 10, // scanning would be done every 100ms
          qrbox: { width: 250, height: 250 },
          disableFlip: false
        },
        (decodedText) => {
          html5QrCode.stop()
          updateResult(decodedText)
          router.push('/result')
        },
        error => { console.log('error', error) }
      )
    } catch (e) {
      console.log('=== ERROR', e)
      if (e instanceof Error) {
        setError(e.message)
      }
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          QR
        </h1>
        <p>{error}</p>
        <button onClick={() => onClick()}>カメラを起動</button>
        <div id='reader' />
      </main>
    </div>
  )
}

export default HtmlQr
